baseURL = "https://broodjeaap.net"
languageCode = "en-us"
title = "BroodjeAap"

theme = "hugo-creative-portfolio-theme"

[params]
    style = "blue"
    description = "BroodjeAap Projects"
    
    # Nav links in the side bar

    [[params.navlinks]]
    name = "Projects"
    url = "projects"
    home = true

    [[params.navlinks]]
    name = "About"
    url = "about/"


    [params.social]
    email         = "david@broodjeaap.net"
    twitter       = "https://twitter.com/BroodjeAap89"
    linkedin      = "https://www.linkedin.com/in/david-zessen-10626872/"
    instagram     = "https://www.instagram.com/davidzessen/"
    github        = "https://github.com/broodjeaap"
    youtube       = "https://www.youtube.com/user/Broodjeaap89"